# Generated by Django 4.1.3 on 2022-12-26 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myvideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=home.models.UploadToPathAndRenameVideo('media/video/'))),
                ('video_description', models.TextField(blank=True, null=True)),
                ('folder_created_date', models.DateTimeField(auto_now_add=True)),
                ('video_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
