# Generated by Django 4.1.3 on 2022-12-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_myvideos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myvideos',
            old_name='folder_created_date',
            new_name='video_created_date',
        ),
    ]
